name: CI Pipeline & Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    # 3. Install Dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Set Environment Variables & Run Training
    - name: Run Model Training (Test Run)
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        python MLProject/modelling_tuning.py

    # Menyimpan artefak ke GitHub Repository (Actions Tab)
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: final-model-data      # Nama file zip 
        path: MLProject/online-sales-dataset_preprocessing.csv # File yang akan disimpan
        retention-days: 5

    # 5. Build Docker Image
    - name: Build Docker Image
      run: |
        # Membuat Dockerfile sederhana secara dinamis
        echo "FROM python:3.9-slim" > Dockerfile
        echo "WORKDIR /app" >> Dockerfile
        echo "COPY requirements.txt ." >> Dockerfile
        echo "RUN pip install -r requirements.txt" >> Dockerfile
        echo "COPY . /app" >> Dockerfile
        echo "CMD [\"python\", \"MLProject/modelling_tuning.py\"]" >> Dockerfile
        
        # Build image dengan tag 'latest'
        docker build -t ${{ secrets.DOCKER_USERNAME }}/submission-sml:latest .

    # 6. Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. Push Image to Docker Hub (Syarat Advanced)
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/submission-sml:latest
